//	TECH 2251
//	Advanced Programming Technology
//	Fall 2019
//	The University of Memphis
//
//	Assignment:		Lecture 7-2 Program 1
//	Developer:		Todd S. Canaday
//	Version:		1.0
//	Compiler:		Java ver. 1.8.0_221
//	Date:			August 2, 2019
//
//	Program Description:
//	
//	Example Java program demonstrating the use of the
//	Calendar and Gregorian Calendar classes...

import java.util.Calendar;
import java.util.GregorianCalendar;

public class Calendar_Test
{
	public static void main(String[] args)
	{
		//	create an instance of the Gregorian calendar...
		GregorianCalendar gc = new GregorianCalendar();
		
		//	set the calendar...
		gc.set(Calendar.YEAR, 1939);				//	year is 2016...
		gc.set(Calendar.MONTH, Calendar.SEPTEMBER);	//	month is October...
		gc.set(Calendar.DAY_OF_MONTH, 1);			//	day is 31...

		//	get the calendar settings just performed...
		int theSetMonth = gc.get(gc.MONTH);			//	get the set month...
		int theSetDay = gc.get(gc.DAY_OF_MONTH);	//	get the set day of the month...
		int theSetYear = gc.get(gc.YEAR);			//	get the set year...
		
		//	print out the calendar settings...
		System.out.println("theSetMonth is:  " + (theSetMonth+1));	//	months are indexed beginning with 0...
		System.out.println("theSetDay is:    " + theSetDay);		//	print out the day...
		System.out.println("theSetYear is:   " + theSetYear);		//	print out the year...
		
		//	print out line seperator...
		System.out.println();
		
		//	print out the calendar info using the MM/DD/YYYY format...
		System.out.print("The date in MM/DD/YYYY format is:  ");
		System.out.println((theSetMonth+1) + "/" + theSetDay + "/" + theSetYear);
		
		//	print out line seperator...
		System.out.println();
		
		//	see if this is a leap year...
		boolean leapYr = gc.isLeapYear(theSetYear);
		//	determine the actual day of the year...
		int dayOfYear = gc.get(gc.DAY_OF_YEAR);
		
		System.out.println("The Day is " + gc.get(gc.DAY_OF_WEEK));
		
		System.out.println("Is the year " + theSetYear + " a leap year?  " + leapYr);
		System.out.println();
		System.out.print("If the date is " + (theSetMonth+1) + "/" + theSetDay + "/" + theSetYear + ", then");
		System.out.println(" the day of the year is " + dayOfYear + ".");			//	print out the day of the year....
	}
}
